export const CART_ACTIONS = {
  INIT: 'INIT',
  ADD: 'ADD',
  REMOVE: 'REMOVE',
  REMOVE_MULTIPLE: 'REMOVE_MULTIPLE',
  UPDATE_QTY: 'UPDATE_QTY',
  TOGGLE_SELECT: 'TOGGLE_SELECT',
  SELECT_ALL: 'SELECT_ALL',
  UNSELECT_ALL: 'UNSELECT_ALL',
  CLEAR: 'CLEAR',
};
